name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci_example:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test and create coverage report
      run: |
        dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:./CoverageReport -reporttypes:Html
        ls -la
        cd CoverageReport
        ls -la
    - name: Upload test coverage report
      uses: actions/upload-artifact@v2
      with:
        name: CoverateReport
        path: /home/runner/work/dotnet_ci/dotnet_ci/src/CoverageReport
        
